# Generated by Django 3.2.5 on 2021-09-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
