# Generated by Django 3.2.5 on 2021-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='contents',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=40),
        ),
    ]
